# Generated by Django 3.0.4 on 2020-03-20 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='CustomUserWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=2000)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=50, null=True, unique=True)),
                ('ref_phone_number', models.CharField(blank=True, default='123456', max_length=50)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic')),
                ('b_name', models.CharField(blank=True, max_length=100, null=True)),
                ('b_address', models.CharField(blank=True, max_length=200, null=True)),
                ('b_branch_address', models.CharField(blank=True, max_length=200, null=True)),
                ('b_employe_number', models.IntegerField(blank=True, null=True)),
                ('b_contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('b_phone_number', models.IntegerField(blank=True, null=True)),
                ('b_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('b_website', models.CharField(blank=True, max_length=200, null=True)),
                ('b_twitter_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('b_facebook_profile', models.CharField(blank=True, max_length=200, null=True)),
                ('b_annual_print_budget', models.IntegerField()),
                ('b_logo', models.ImageField(blank=True, null=True, upload_to='b_logo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
